# check out all of our support receivers, processors, exporters, extensions here: https://github.com/SumoLogic/sumologic-otel-collector/tree/main?tab=readme-ov-file#sumo-logic-distribution-for-opentelemetry-collector
# you can add custom collector tags using the sumologic extension and the collector_fields parameter
extensions:
  sumologic:
    collector_fields:
      customfield: customvalue
# receivers read from the logs and metrics on the server (i.e. windows events and host metrics)
receivers:
  # windows event logs configuration - see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.124.1/receiver/windowseventlogreceiver
  windowseventlog/application:
    channel: Application
    operators:
    - type: add
      field: resource["_sourceName"]
      value: Application
  windowseventlog/security:
    channel: Security
    operators:
    - type: add
      field: resource["_sourceName"]
      value: Security
  windowseventlog/system:
    channel: System
    operators:
    - type: add
      field: resource["_sourceName"]
      value: System
  # host metrics configuration - see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.124.1/receiver/hostmetricsreceiver
  hostmetrics:
    collection_interval: 1m
    scrapers:
    cpu:
      metrics:
      system.cpu.utilization:
        enabled: true
    load: null
    memory:
      metrics:
      system.memory.utilization:
        enabled: true
    disk: null
    filesystem:
      metrics:
      system.filesystem.utilization:
        enabled: true
    network: null
    paging: null
    process:
      exclude:
      match_type: strict
      names:
        - null
      mute_process_exe_error: true
      mute_process_io_error: true
      mute_process_name_error: true
      metrics:
      process.threads:
        enabled: true
      process.cpu.utilization:
        enabled: true
      process.memory.utilization:
        enabled: true
      process.disk.operations:
        enabled: true
# processors allow you to perform additional actions on data before sending to sumo (i.e. filtering, tagging, etc)
processors:
  resource/windows_resource_attributes:
    attributes:
    - key: sumo.datasource
      value: windows
      action: insert
    - key: _contentType
      value: OpenTelemetry
      action: insert
    - key: _sourceCategory
      value: otel/windows
      action: insert
  resource/windows_resource_attributes/metrics:
    attributes:
    - key: _source
      value: windows/hostmetrics
      action: insert
    - key: _sourceName
      value: windows
      action: insert
  resource/windows_resource_attributes/logs:
    attributes:
    - key: _source
      value: windows/windowseventlog
      action: insert
# services define the pipelines that connect receivers, processors and exporters
service:
  pipelines:
    metrics/windows:
    receivers:
      - hostmetrics
    processors:
      - memory_limiter
      - resourcedetection/system
      - resource/windows_resource_attributes/metrics
      - resource/windows_resource_attributes
      - batch
    exporters:
      - sumologic
    logs/windows:
    receivers:
      - windowseventlog/application
      - windowseventlog/system
      - windowseventlog/security
    processors:
      - memory_limiter
      - resourcedetection/system
      - resource/windows_resource_attributes/logs
      - resource/windows_resource_attributes
      - batch
    exporters:
      - sumologic